### ISSUE TITLE
Fix error when nothing to commit in actions

### ISSUE THREAD

**Issue by AlertRED** [JohnTitor/2k36.org-old#307]
Hello. If I totally understand problem in your CI code for load of sponsors, you can add something like that, to CI don't show errors in actions.

```shell
if [[ $(git diff --cached --numstat | wc -l) != 0 ]]; then
...
fi
```

https://github.com/JohnTitor/2k36.org/blob/6c1da5d26150d514ced40927ea26617194169e04/.github/workflows/sponsors.yml#L47-L48

**Comment by JohnTitor** [comment]
Thanks! Fixed by https://github.com/JohnTitor/2k36.org/commit/6a4e6ef3e1021ef7562080bed247b9dcede8b702.
